# Generated by Django 5.0.6 on 2024-06-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='industry',
            new_name='Industries',
        ),
    ]
