# Generated by Django 5.0.6 on 2024-06-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_alter_company_options_alter_industry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industry'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Industries',
            new_name='Industry',
        ),
    ]
