# Generated by Django 5.0.6 on 2024-06-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0004_alter_industry_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Industry',
            new_name='industry',
        ),
    ]
