# Generated by Django 5.0.6 on 2024-06-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0005_rename_industry_company_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='companies',
            new_name='company',
        ),
    ]
