# Generated by Django 5.0.6 on 2024-06-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0006_rename_companies_person_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='company',
            new_name='companies',
        ),
    ]
